name: Java CI [pr]

on:
  pull_request:
    branches: [ master ]

jobs:
  pr_autotesting:
    runs-on: ubuntu-latest
    steps:

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Cloning the repository
        uses: actions/checkout@v3

      - name: Run tests
        run: ./gradlew test